// System call numbers
#define SYS_fork   1
#define SYS_exit   2
#define SYS_wait   3
#define SYS_pipe   4
#define SYS_read   5
#define SYS_kill   6
#define SYS_exec   7
#define SYS_fstat  8
#define SYS_chdir  9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_pause  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_ps     22
#define SYS_halt   23
#define SYS_sem_open  24
#define SYS_sem_wait  25
#define SYS_sem_post  26
#define SYS_sem_get   27
#define SYS_sem_close 28
#define SYS_shmget    29
#define SYS_shmat     30
#define SYS_shmdt     31
#define SYS_lseek     32
#define SYS_waitpid   33
#define SYS_sched_algorithm 34
#define SYS_settimeslice   35
#define SYS_gettimeslice   36
#define SYS_cgettimeofday  37
#define SYS_schedstat      38
#define SYS_sched_setburst 39
#define SYS_banker_init          40
#define SYS_banker_setmax        41
#define SYS_banker_request       42
#define SYS_banker_release       43
#define SYS_banker_safe_sequence 44
#define SYS_banker_get_state     45
#define SYS_banker_setmax_alloc  46
#define SYS_mon_create           47
#define SYS_mon_lock             48
#define SYS_mon_unlock           49
#define SYS_mon_wait             50
#define SYS_mon_signal           51
#define SYS_mon_broadcast        52
#define SYS_deadlock_set         53
#define SYS_setpriority          54
#define SYS_getpriority          55
#define SYS_rt_register          56
#define SYS_rt_wait_period       57
#define SYS_getcpuid             58
#define SYS_setcpuaffinity       59
#define SYS_msgget               60
#define SYS_msgsnd               61
#define SYS_msgrcv               62
