// Scheduling algorithm API
// Provides runtime scheduling algorithm switching capability
// Note: sched_algorithm() is auto-generated by usys.pl

#include "kernel/types.h"
#include "user/user.h"

const char* sched_algorithm_name(int algo) {
  switch (algo) {
  case 0:
    return "RR";
  case 1:
    return "FCFS";
  case 2:
    return "MLFQ";
  default:
    return "UNKNOWN";
  }
}
