#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("waitpid");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("lseek");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("getcwd");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");
entry("ps");
entry("halt");
entry("sem_open");
entry("sem_wait");
entry("sem_post");
entry("sem_get");
entry("sem_close");
entry("shmget");
entry("shmat");
entry("shmdt");
entry("socket");
entry("bind");
entry("sendto");
entry("recvfrom");
entry("sched_algorithm");
entry("settimeslice");
entry("gettimeslice");
entry("cgettimeofday");
entry("schedstat");
entry("sched_setburst");
entry("banker_init");
entry("banker_setmax");
entry("banker_request");
entry("banker_release");
entry("banker_safe_sequence");
entry("banker_get_state");
entry("banker_setmax_alloc");
entry("mon_create");
entry("mon_lock");
entry("mon_unlock");
entry("mon_wait");
entry("mon_signal");
entry("mon_broadcast");
entry("deadlock_set");
entry("setpriority");
entry("getpriority");
entry("rt_register");
entry("rt_wait_period");
entry("getcpuid");
entry("setcpuaffinity");
entry("msgget");
entry("msgsnd");
entry("msgrcv");
